FROM node:16-alpine AS builder

RUN apk add --no-cache curl

RUN curl -L https://github.com/stirante/facaccimo/archive/refs/heads/master.tar.gz | tar xzf - -C /

WORKDIR /facaccimo-master

RUN npm install

RUN npm run build



FROM node:16-alpine AS runner

RUN mkdir -p /facaccimo/dist

COPY --from=builder /facaccimo-master/dist /facaccimo/dist

WORKDIR /facaccimo

RUN npm install -g serve

EXPOSE 8080

CMD ["serve", "-s", "dist", "-l", "8080"]

