FROM python:3

WORKDIR /cubarimoe
COPY ./requirements.txt .
RUN pip install -r requirements.txt

ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE=docker.settings_env

ENV MEMCACHED=
ENV DB_NAME=
ENV DB_USER=
ENV DB_PASS=
ENV DB_HOST=
ENV DB_PORT=

COPY . ./

EXPOSE 8000
